### ISSUE TITLE
v0.7.1 fails to login - DOMException: Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by dreiekk** [dreiekk/calcdav#57]
> DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by jorge-leon** [comment]
Hi,
I got the same exception when testing.  Do you want a log file from the developer tools?

**Comment by dreiekk** [comment]
Thanks for your support!
I just sorted it out. It seems to be a problem with the DOM elements of all animated icons not being accessible through vue.
